apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kuberspring-app-deployment
spec:
  selector:
    matchLabels:
      app: kuberspring-app
  replicas: 1 # tells deployment to run 1 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: kuberspring-app
    spec:
      containers:
      - name: kuberspring-app
        image: roamingthings/kuberspring
        imagePullPolicy: Never
        env:
        - name: PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: order-db-secret
              key: password
        ports:
        - containerPort: 8080
          name: server

---
apiVersion: v1
kind: Service
metadata:
  name: kuberspring
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: kuberspring-app